Fix squadsize achievement improperly triggering
WOTCStrategyOverhaul/CovertInfiltration pull request #652
Opened 2021-05-19 03:23 UTC by cannonfodder1

Closes #586 
After testing this, I am now a retired XCOM 2 achievement hunter

2021-05-19 07:03 UTC, Xymanek requested changes

2021-05-19 07:03 UTC, Xymanek commented on CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration.uc
> +	Template.AddCHEvent('HasIncreasedSquadSize', HasIncreasedSquadSize, ELD_Immediate, 99);
The hook/event name is too ambiguous - e.g. one could think that it controls the number of slots on the squad select. I suggest `AllowNoSquadSizeUpgradeAchivement`.

Speaking of hooks - I don't see a CHL issue/pr?

2021-05-21 10:39 UTC, Xymanek commented
Blocked by discussion in https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/994

2021-06-11 06:11 UTC, Xymanek commented
CHL PR merged

2021-06-16 11:20 UTC, Xymanek commented
Please rebase (the current master's submodule already points to a CHL version with the event implemented)

2021-06-18 05:23 UTC, Xymanek commented
The submodule is still changed in the diff?

2021-06-18 05:30 UTC, cannonfodder1 commented
> The submodule is still changed in the diff?

Uh oh I might have screwed up, this branch's CHL is up to date with the CHL master, but CI's master's CHL is a few commits behind

2021-06-18 05:33 UTC, Xymanek commented
Ideally I would prefer if the submodule completely went away from this PR's diff

2021-06-18 05:36 UTC, Xymanek approved these changes

2021-06-18 05:36 UTC, merged